// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6D-Skr7S1jqBREgdVPRdzaEvy_ph_D3U',
    appId: '1:407385730713:web:b15773e3e225f37a7a5208',
    messagingSenderId: '407385730713',
    projectId: 'q-it-46b42',
    authDomain: 'q-it-46b42.firebaseapp.com',
    storageBucket: 'q-it-46b42.firebasestorage.app',
    measurementId: 'G-2J7LFVT2F3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcbjX8jwppDcASth0blwoEREj1EybYuR8',
    appId: '1:407385730713:android:b02957c0372e8cd37a5208',
    messagingSenderId: '407385730713',
    projectId: 'q-it-46b42',
    storageBucket: 'q-it-46b42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZOyeL1_NYtUMJ2cToxa7pYIodA_Skxp4',
    appId: '1:407385730713:ios:d2e48f558fe7a1347a5208',
    messagingSenderId: '407385730713',
    projectId: 'q-it-46b42',
    storageBucket: 'q-it-46b42.firebasestorage.app',
    androidClientId: '407385730713-aelrnv8hjimkihqu8bf75ln0aru6pbe3.apps.googleusercontent.com',
    iosClientId: '407385730713-j854or5i7asokf02cfkb1gobmf14jk2e.apps.googleusercontent.com',
    iosBundleId: 'com.bapan.cartify',
  );

}